print('hello'.isalpha())
print('Hello123'.isalpha())
print('Hello'.isalnum())
print('123'.isdecimal())
print(' '.isspace())
print('The return value is always a Boolean')
print("Hello World, How Are you".istitle)
print("hello world".title())
print("Mahesh Shelikeri".startswith("Mahe"))
print('India'.startswith('abcd'))
print('I love India'.endswith('India'))
